### PR TITLE
added memory optimizations and slight modifications

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @ing-bank, @ymwdalex, @aerdem4, @Vegoo89 and anyone else I haven't mentioned (Attention: @Bergvca)

First of all, many thanks for this truly awesome library!

We've been making heavy use of it as the core of our application '[string_grouper](https://github.com/Bergvca/string_grouper)'.  For the most part, that would have been enough except that during further optimization I came across an issue that I thought would best be solved if I could attempt a slight variation to your package.  So I thought I'd inquire to see what you think.

The issue is this: sparse_dot_topn, as it is now, requires the integer `ntop` as an argument to limit and allocate memory for the output, but it is often not known beforehand what `ntop` should be if one wants to, say, capture ***all*** results above `lower_bound`.  

Of course one may simply choose `ntop = n_cols` to achieve this goal, but in cases of limited memory resources (or very large datasets), this could prove to be a prohibitive over-estimation, raising an out-of-memory exception, as can be seen from the following result (from running sparse_dot_topn on my intel Core i7, 16GB Memory laptop):

```cmd
(sparse_dot_topn) C:\Users\runner\eclipse-workspace\sparse_dot_topn>python example\comparison2.py
ntop = 10000
threshold = 0.01
density = 1e-06
nr_vocab = 33554432
n_samples = 1000000
n_duplicates = 10000
nnz_a = 33554432
nnz_b = 335544

Non-parallelized sparse_dot_topn function
Traceback (most recent call last):
  File "C:\Users\runner\eclipse-workspace\sparse_dot_topn\example\comparison2.py", line 53, in <module>
    rtv = timeit.timeit('awesome_cossim_topn(a, b, N, thresh)',
  File "C:\Program Files\Python39\lib\timeit.py", line 233, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "C:\Program Files\Python39\lib\timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "c:\users\runner\eclipse-workspace\sparse_dot_topn\sparse_dot_topn\awesome_cossim_topn.py", line 58, in awesome_cossim_topn
    data = np.empty(nnz_max, dtype=A.dtype)
numpy.core._exceptions.MemoryError: Unable to allocate 74.5 GiB for an array with shape (10000000000,) and data type float64
```

Here is where I come in with a _slightly_ modified function to compute the matrix product and return ***all*** results greater than `lower_bound` but without any need to specify `ntop` as an argument.  This is because the function leaves it up to C/C++ (specifically, an STL vector) to manage/grow/allocate/reallocate memory as the results are computed and then returns the result to python (in a numpy array).  For this purpose, using cython, I created a new extension called `array_wrappers` that enables numpy ndarrays to simply point to the location where C++ stored the computed results and thus avoid copying them.  The result is that data-set inputs can now be increased over a hundredfold without having to worry about running out of memory:

```cmd
(sparse_dot_topn) C:\Users\runner\eclipse-workspace\sparse_dot_topn>python example\comparison2.py
Timings
python vs C/C++ memory management

ntop = 1000000
threshold = 0.01
density = 1e-06
nr_vocab = 33554432
n_samples = 1000000
n_duplicates = 1000000
nnz_a = 33554432
nnz_b = 33554432

Non-parallelized sparse_dot_topn function
python          C/C++
     _        42.1645
Threaded function with 1 thread
python          C/C++
     _        47.0010
Threaded function with 2 threads
python          C/C++
     _        31.7335
Threaded function with 3 threads
python          C/C++
     _        26.6192
Threaded function with 4 threads
python          C/C++
     _        24.1530
Threaded function with 5 threads
python          C/C++
     _        23.4181
Threaded function with 6 threads
python          C/C++
     _        22.3574
Threaded function with 7 threads
python          C/C++
     _        21.6728
Scipy+numpy original function
<could not wait for it :)>
``` 

Secondly, in our application `string_grouper`, it turns out that it is often useful to know after computing the cosine similarities, whether `ntop`, when specified, was large enough to capture all the results above `lower_bound`.  So the new function has been further slightly modified so that it not only returns the matrix-product results constrained by the given `ntop` and `lower_bound`, but also returns the value of what `ntop` should have been to capture all results above `lower_bound` (so watch out for backward compatibility of `awesome_cossim_topn` here!).

I've implemented both threaded and non-threaded versions for all functions.  

The new functions are also slightly more efficient than before due to the following optimizations:

1. In the C++ code, instead of assigning one potentially long STL vector to another, I use the `swap` attribute function of `std::vector`, which avoids actual copying of data and thus runs in constant amortized time instead of linear.

2. When gathering the computed data from C++ into the numpy arrays, the previous version did it serially, so I parallelized that operation too.

Timing comparisons can be seen from the following results:

<table style="width:100%">
  <tr>
    <th>Old Version Timings</th>
    <th>New Version Timings</th>
  </tr>
  <tr valign=top>
    <td>
ntop = 1000<br>
threshold = 0.01<br>
density = 1e-06<br>
nr_vocab = 33554432<br>
n_samples = 1000000<br>
n_duplicates = 1000<br>
nnz_a = 33554432<br>
nnz_b = 33554<br>
<br>
Non-parallelized sparse_dot_topn function<br>
 2.3597<br>
Threaded function with 1 thread<br>
 2.4689<br>
Threaded function with 2 threads<br>
 1.3271<br>
Threaded function with 3 threads<br>
 1.1089<br>
Threaded function with 4 threads<br>
 1.0228<br>
Threaded function with 5 threads<br>
 0.9681<br>
Threaded function with 6 threads<br>
 0.9172<br>
Threaded function with 7 threads<br>
 0.8443<br>
Scipy+numpy original function<br>
181.9077616<br>
</td>
<td>
ntop = 1000<br>
threshold = 0.01<br>
density = 1e-06<br>
nr_vocab = 33554432<br>
n_samples = 1000000<br>
n_duplicates = 1000<br>
nnz_a = 33554432<br>
nnz_b = 33554<br>
<br>
Non-parallelized sparse_dot_topn function<br>
python    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      C/C++<br>
 2.1610     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     2.1510<br>
Threaded function with 1 thread<br>
python    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      C/C++<br>
 2.2272    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      2.2554<br>
Threaded function with 2 threads<br>
python    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      C/C++<br>
 1.2242   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       1.2040<br>
Threaded function with 3 threads<br>
python   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       C/C++<br>
 0.9231    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      0.9088<br>
Threaded function with 4 threads<br>
python   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       C/C++<br>
 0.9618   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       0.9420<br>
Threaded function with 5 threads<br>
python   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       C/C++<br>
 0.9072   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       0.8540<br>
Threaded function with 6 threads<br>
python   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       C/C++<br>
 0.7751   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       0.8064<br>
Threaded function with 7 threads<br>
python &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        C/C++<br>
 0.7289 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         0.7385<br>
Scipy+numpy original function<br>
185.1595374
</td>
</tr>
</table>

### CODE REVIEW

**Comment by aerdem4** [comment]
Hi @ParticularMiner , thanks for your interest in the package and your PR. It can be indeed nice to have flexibility on topn, you have a legit use case. I didn't read the whole code yet but I currently have only one concern: 

> So the new function has been further slightly modified so that it not only returns the matrix-product results constrained by the given ntop and lower_bound, but also returns the value of what ntop should have been to capture all results above lower_bound (so watch out for backward compatibility of awesome_cossim_topn here!).

It may be better to have a flag like return_counts parameter of np.unique (something like return_best_recall_topn). This parameter can be set to False by default. Then people who update our package don't need to make any modifications on their code. I wonder what @ymwdalex thinks also.

**Comment by ParticularMiner** [comment]
Hi @aerdem4 ,

Thanks for your quick reply.   Your suggestion makes sense, in fact it had crossed my mind before, so it is good to have it confirmed.  If no one else objects, I’ll update the code in my next commit.

Cheers!

**Comment by ParticularMiner** [comment]
Attention: @ing-bank, @ymwdalex, @aerdem4, @Vegoo89, @Bergvca

Fixed the backward compatibility issue:

As per @aerdem4's suggestion, I've added a flag `return_best_topn` to `awesome_cossim_topn` which is `False` by default.  If `return_best_topn=True`, the function will return the true maximum number of elements > `lower_bound` per row of _A_ * _B_ together with _C_ = [sorted top _n_ results > `lower_bound` for each row of _A_ * _B_] in a tuple; otherwise, only _C_ is returned as in the previous versions.

**Comment by ParticularMiner** [comment]
In the latest forced commits, I removed all references to `string_grouper` (our application), which I had mistakenly left within comments and error messages in `awesome_cossim_topn`.  (I had been testing the latest code with `string_grouper`, hence their existence.)  Sorry about that.

**Comment by ParticularMiner** [comment]
Hi @ing-bank, @ymwdalex, @aerdem4, @Vegoo89, @Bergvca

In my latest commit, I've modified the code in such a way that regardless of the given value of `ntop`, `awesome_cossim_topn` will always first let python attempt to allocate memory for the result matrix before handing over to C/C++ for computation.  This is how `awesome_cossim_topn` has always been till now.  Note that this allocation's size is often a gross over-estimate.

But now if python's memory allocation fails and a `MemoryError` exception is raised, then C/C++ will handle the memory allocation (regardless of the given value of `ntop`), allocating memory only as needed, as it performs the computation.

I'm not sure why or how, but results seem to indicate that C/C++ often performs slightly better/faster when it does the computation while also handling the memory allocation than when it does only the computation (that is, when python allocated the memory).  I had thought it would be the other way around.

Because of this, I’m wondering whether to simply replace the original function (both serial and parallel) with the new ones, thus keeping the code short.

**Comment by ParticularMiner** [comment]
Hi @ing-bank, @ymwdalex, @aerdem4, @Vegoo89

Sorry, I just realized that the test samples in my previous post were somewhat unrealistic: for instance, n_vocab was atypically large for such a small density.  Thus the product-matrix ***A***\****B*** had far too few nonzero elements.  Actually, I had blindly re-used some values I found in some scripts in the repository. 

A more typical sample would have n_vocab ~ 26<sup>3</sup> (for 3-grams of the Latin alphabet); with density ~ 30/n_vocab (for 30-character-length  strings).    So I re-run the tests with these values and it became clear that the C/C++ memory reallocations do in fact slow the program down considerably (almost 4 times!).  So I apologize for the previous misleading claims.

In the end, I find it is better to have a separate fast "*scouting*" function that, before the actual computation, goes ahead and determines the amount of space needed for the memory allocation.  Python then makes the allocation based on the information gathered by the "*scout*", and proceeds to do the matrix-product computation.  The "*scout*" will only be called upon whenever the quick over-estimate for the memory-allocation is too large and leads to a `MemoryError` exception.  

Here are the timing results from the improved tests:

---

### Table comparing average time-durations of `awesome_cossim_topn` (for the old and new versions) over 16 random samples of typical language-processing matrix-pairs _A_ and _B_.


The column-names show how the memory was allocated for the matrix-product ***A***\****B*** result &mdash; either the size was 
1. overestimated as `ntop*A.shape[0]`, or
2. determined exactly by the '*scout*' function before the actual computation.

Remember that the old version had no *scouting* function.

Again, note that the new version computes the matrix-product ***A***\****B*** while also computing extra information (namely, the true maximum number of matches above the threshold similarity per row of the matrix-product ***A***\****B***); the old version does not compute any extra information.

Time is measured in seconds (on my 16GB RAM, Intel Core i7 CPU @2.20 GHz laptop).  

|#threads| **over-estimate (old version)**|**over-estimate (new version)**|**by scout (new version)**|**&pm; percentage time-increase when using scout**|
|---:|---:|---:|---:|---:|
|0|         9.548760|         9.649388|10.826448|+12.2%|
|1|       16.259485|        12.478173|13.848332|+11.0%|
|2|         9.551608|         7.513212|7.888855|+5.0%|
|3|         7.883986|        6.325500|6.476630|+2.4%|
|4|         7.010394|        5.379746|5.409104|+0.6%|
|5|         6.415807|        4.860059|4.792095|-1.3%|
|6|         6.019867|        4.487826|4.335973|-3.4%|
|7|         5.786934|       4.258750|4.058920|-4.5%|

#matrix_pairs = 16
ntop = 1&nbsp;000
threshold = 0.01
nr_vocab = 26<sup>3</sup> = 17&nbsp;576 (the number of columns of ***A*** = number of rows of ***B***)
density = 30/n_vocab = 0.0017
n_samples = 1&nbsp;000&nbsp;000 (the number of rows of ***A***)
n_duplicates = 1&nbsp;000  (the number of columns of ***B***)
nnz(***A***) = 30&nbsp;000&nbsp;000  (the number of nonzero components of ***A***)
nnz(***B***) = 30&nbsp;000  (the number of nonzero components of ***B***)

nnz(***A***\****B***) = 47&nbsp;108&nbsp;224 &pm; 18&nbsp;498   (mean and standard deviation of the total number of nonzero components of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)

ntop(***A***\****B***) = 108 &pm; 3  (mean and standard deviation of the true maximum number of nonzero components per row of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)
 
---
As you can see from the table, for the larger numbers of threads, the effect of the '*scout*' on the speed of computation is negligible and even boosting.  

In fact, now that I've done the speed-measurements properly, I see that the gains the new version has made on the old must be due to other optimizations I made for the multi-threaded functions, namely:

the old version's multi-threaded implementation in the C/C++ code used a typically very large vector of vectors, with length equal to the number of rows of ***A***.  This is generally not recommended for performance-critical applications.  The new version tries to avoid this by instead using only 2 small vectors of vectors, each with length equal to the number of threads, which is, typically, a much smaller number.  The result is that the used memory is leaner and less fragmented during the run.

Secondly, the old version was not thoroughly parallelized &mdash; the final task of copying the computed results into the output CSR matrix arrays remained serial.  In the new version this task is now parallelized, thus achieving complete parallelization of the code.

Now we indeed have the best of both worlds: increased speed and improved memory-management.

My last commit therefore discards the previous C/C++ memory-management routines and includes these latest optimizations.  
You'll find them in the new PR #52.  I will therefore close this PR.

**Pull request closed without merging**
