### PR TITLE
remove pyproject.toml

### PR DESCRIPTION
**Pull request by stephanecollot**
To fix issue #48

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@stephanecollot  I had a discussion with @ymwdalex, the formal way of solving this problem is actually put `oldest-supported-numpy` in `pyproject.toml`. Something like below:

```toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta" 
```

**Comment by stephanecollot** [comment]
I already tried this, it didn't work.

**Comment by TonyXiang8787** [comment]
You also need to remove `setup_requires` from `setup.py`. And add `cython` in `pyproject.toml`.

When you test it, create a new virtual environment.

**Comment by stephanecollot** [comment]
oldest-supported-numpy put a very loose limit on numpy depending on python version see: https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg


Only 3 solutions I see:
- deleting pyproject.toml to disable build isolation and publish only sdist to Pypi and no wheels. That works, and I'm 90% sure that it won't impact any body in a negative way.
- fixing numpy to a very high version, (e.g now 1.22 if I'm correct), and do it at every numpy release, not cool for maintenance and for the users
- rewriting the package with pybind

**Comment by TonyXiang8787** [comment]
@stephanecollot  that's exactly the purpose of `oldest-supported-numpy`. To provide a `numpy` version as old as possible in build time. `numpy` C API is forward compatible. If you build your package using the oldest possible numpy, your package can run also on newer versions of `numpy`.

Note the difference between build-time dependencies (in `pyproject.toml`) which are installed in build isolation and run-time dependencies.

**Comment by TonyXiang8787** [comment]
You also don't need to put `cython` in your `install_requires`. `cython` is almost never needed in runtime, it is a build-time dependency.

**Comment by stephanecollot** [comment]
Thank you, now I understand!
You need to install the oldest possible version of numpy at build time, because it is forward compatible for new version of numpy for run time.
If you don't fix the version of numpy at build time, it installs the latest version for building, which not backward compatible with older version of numpy.

Related to `setup_requires`, you are right, it is deprecated, and the new way is `pyproject.toml`:
https://github.com/pypa/setuptools/issues/1320#issuecomment-380093653
https://github.com/pypa/setuptools/issues/2823

Zhe tested it out and it works!

**Comment by ymwdalex** [comment]
This issue was fixed by #67

**Pull request closed without merging**
