### PR TITLE
Use fully qualified `std::`

### PR DESCRIPTION
**Pull request by shadchin**
This fixes a compilation error in a really arcane environment I use. Anyway, `std` should be there.

### CODE REVIEW

**Comment by shadchin** [comment]
It seems that the fall in tests is not related to PR

**Comment by stephanecollot** [comment]
Yes it seems there are some different ordering of the results:
```>           assert awesome_result_top3 == sparse_result_top3
E           assert [[(358, 6.525...345856)], ...] == [[(358, 6.525...345856)], ...]
E             At index 202 diff: [(222, 5.1337743), (113, 5.1337743), (209, 4.973848)] != [(113, 5.1337743), (222, 5.1337743), (209, 4.973848)]
[...]
tests\sparse_dot_topn\test_awesome_cossim_topn.py:278: AssertionError
=========================== short test summary info ===========================
FAILED tests/sparse_dot_topn/test_awesome_cossim_topn.py::test_awesome_cossim_top_small_matrix[0-float32]
```
I'm clicking retry to see if it is random.

**Comment by stephanecollot** [comment]
Yes it was random. I merge.

**Comment by stephanecollot** [comment]
FYI it is released in 0.3.4

**Pull request merged**
